package g

const (
	NEWLINE = "newline"
	INT     = "int"
	SIN     = "sin"
	COS     = "cos"
	TAN     = "tan"
	ARCSIN  = "arcsin"
	ARCCOS  = "arccos"
	ARCTAN  = "arctan"
	EXIT    = "exit"
	QUIT    = "quit"
	LOG     = "log"
	LN      = "ln"
	SQRT    = "sqrt"
	LPAREN  = "("
	RPAREN  = ")"
	POW     = "**"
	SUM     = "+"
	DIFF    = "-"
	QUOT    = "/"
	PROD    = "*"
	ASSIGN  = "="
	LIST    = "list"
	CLEAR   = "clear"
	ABS     = "abs"
)
